
acl internal { 10.0.0.0/8; 10.18.0.1/32; 10.18.0.2/32; 10.28.0.1/32; 10.28.0.2/32; 78.47.110.152/32; 94.130.183.229/32; 127.0.0.0/8; 172.16.0.0/16; 172.17.0.0/16; 172.18.0.0/16; 172.19.0.0/16; 172.20.0.0/16; 172.21.0.0/16; 172.22.0.0/16; 172.23.0.0/16; 172.24.0.0/16; 172.25.0.0/16; 172.26.0.0/16; 172.27.0.0/16; 172.28.0.0/16; 172.29.0.0/16; 172.30.0.0/16; 172.31.0.0/16; 178.104.223.86/32; 188.40.57.14/32; 188.40.57.58/32; 192.168.0.0/16; 192.168.2.1/32; 192.168.2.100/32; 192.168.87.2/32; 192.168.87.15/32; 192.168.87.44/32; 192.168.88.14/32; 192.168.88.15/32; 192.168.88.44/32; 195.201.17.234/32; };
acl external { 0.0.0.0/0; };


zone "10.in-addr.arpa" {
	type master;
	notify explicit;
	also-notify { 10.18.0.1; };
	file "/etc/bind/10.in-addr.arpa.zone";
	allow-query { internal; };
};


zone "168.192.in-addr.arpa" {
	type master;
	notify explicit;
	also-notify { 10.18.0.1; };
	file "/etc/bind/168.192.in-addr.arpa.zone";
	allow-query { internal; };
};


zone "khms1.de" {
	type master;
	notify explicit;
	also-notify { 10.18.0.1; };
	file "/etc/bind/khms1.de.zone";
	allow-query { external; internal; };
};


zone "fast-rail-transport-international.com" {
	type master;
	notify explicit;
	also-notify { 10.18.0.1; };
	file "/etc/bind/fast-rail-transport-international.com.zone";
	allow-query { external; internal; };
};


zone "khms" {
	type master;
	notify explicit;
	also-notify { 10.18.0.1; };
	file "/etc/bind/khms.zone";
	allow-query { internal; };
};


zone "khms.eu" {
	type master;
	notify explicit;
	also-notify { 10.18.0.1; };
	file "/etc/bind/khms.eu.zone";
	allow-query { external; internal; };
};


zone "khms.westfalen.de" {
	type slave;
	notify no;
	masters { 78.47.110.152; 78.47.110.152; };
	file "slave.khms.westfalen.de";
};

zone "16.172.in-addr.arpa"  { file "/etc/bind/db.empty"; type master; };
zone "17.172.in-addr.arpa"  { file "/etc/bind/db.empty"; type master; };
zone "18.172.in-addr.arpa"  { file "/etc/bind/db.empty"; type master; };
zone "19.172.in-addr.arpa"  { file "/etc/bind/db.empty"; type master; };
zone "20.172.in-addr.arpa"  { file "/etc/bind/db.empty"; type master; };
zone "21.172.in-addr.arpa"  { file "/etc/bind/db.empty"; type master; };
zone "22.172.in-addr.arpa"  { file "/etc/bind/db.empty"; type master; };
zone "23.172.in-addr.arpa"  { file "/etc/bind/db.empty"; type master; };
zone "24.172.in-addr.arpa"  { file "/etc/bind/db.empty"; type master; };
zone "25.172.in-addr.arpa"  { file "/etc/bind/db.empty"; type master; };
zone "26.172.in-addr.arpa"  { file "/etc/bind/db.empty"; type master; };
zone "27.172.in-addr.arpa"  { file "/etc/bind/db.empty"; type master; };
zone "28.172.in-addr.arpa"  { file "/etc/bind/db.empty"; type master; };
zone "29.172.in-addr.arpa"  { file "/etc/bind/db.empty"; type master; };
zone "30.172.in-addr.arpa"  { file "/etc/bind/db.empty"; type master; };
zone "31.172.in-addr.arpa"  { file "/etc/bind/db.empty"; type master; };
